name: base
dependencies:
- nvidia::cudatoolkit=11.3.1
- numpy=1.21.2
- pillow=8.4.0
- pip=21.2.4
- python=3.9.7
- pytorch::pytorch=1.10.0=py3.9_cuda11.3_cudnn8.2.0_0
- scipy=1.7.1
- pytorch::torchvision=0.11.1=py39_cu113
- tqdm=4.62.3
- matplotlib=3.5.1
- seaborn=0.11.2
- nomkl=2.35
- tensorflow=2.4.1
- pip:
  - notebook==6.4.10
  - scikit-learn==1.0.2
  - ipywidgets==7.7.0
